version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-portfolio-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: e7uyBQNUshw=
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: 4LYzDPlZIz4=
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_

volumes:
  mysql_data:
